### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by jlesquembre**
As discussed on slack, add a flake.

I removed the `default.nix`, I'd like to know @yisraeldov opinion about it first. If ok, I'd like to add more things before getting it merged (like update the README)

### CODE REVIEW

**Comment by yisraeldov** [comment]
@jlesquembre I don't really use flakes, so can't comment. But can we leave the `default.nix` and then import it into `flake.nix` for those of us that want to continue to use regular nix?

**Comment by jlesquembre** [comment]
Flakes don't play well with the default.nix file. I think we have 2 options, both are ok with me:
- Close this PR, and ignore flakes (at least until adoption improves)
- Have a flake.nix and a default.nix, and people can choose. In this case, I'll update the PR to clarify that in the readme.

@borkdude What do you prefer?

**Comment by borkdude** [comment]
I'm fine with option 2

**Comment by yisraeldov** [comment]
In the case of #2 be maybe comment out the `.envrc` file so  you need to
choose what one to use.

**Comment by jlesquembre** [comment]
I reverted the changes to .envrc and default.nix, and updated the README.
I tested it from my fork with `nix run github:jlesquembre/neil/flake -- --help`, but once merged `nix run github:babashka/neil -- --help` should work (and run the latest version in the main branch)

**Comment by borkdude** [comment]
Thanks a lot! /cc @bsless

**Pull request merged**
