### PR TITLE
`neil dep upgrade`: allow upgrading from unstable version to more recent unstable version

### PR DESCRIPTION
**Pull request by teodorlu**
Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
    - https://github.com/babashka/neil/issues/180

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/neil/blob/main/CHANGELOG.md) file with a description of the addressed issue.

### Rationale

When working with libraries where there is no stable version released, it's nice to be able to upgrade to most recent unstable version. We could allow this with `neil dep upgrade`.

### Proposed semantics

1. A version will never be superseded by an older version
2. A stable version will be superseded by stable versions only
3. Unstable versions will be replaced by the latest version - whether stable or unstable.

### CODE REVIEW

**Comment by teodorlu** [comment]
Let's say I'm on `mylib 0.1-alpha`. There is both a more recent stable version, `mylib 0.2`, and a more recent unstable version `mylib 0.3-alpha`.

What version do we want `neil dep upgrade` to pick?

**Comment by teodorlu** [comment]
I'm leaning towards "if you are currently on an unstable version, you get the latest version period". In the example above, I'd be upgraded to `mylib 0.3-alpha`.

**Comment by borkdude** [comment]
@teodorlu Two minor things:

- There is a temporary test task
- The `neil` script is half-regenerated but not with the latest changes?

**Comment by teodorlu** [comment]
Yes, both need to be fixed before we consider merging! I guess I could have reverted back to a "draft pr" state, this isn't quite done yet.

I tried making the "prefer stable versions change", and started out writing the `preferred-upgrade-version` function with tests. Which worked as I expected. Then I tried to integrate it with the rest of Neil, and just got stuck. So I threw away my local changes, and decided I'd try again later!

**Comment by borkdude** [comment]
OK, please ping me when I should review again :)

**Comment by teodorlu** [comment]
Will do! I'll mark this as draft for now, and move it back to ready for review next time.

**Comment by teodorlu** [comment]
I'm throwing this PR away and trying again in #180 !

**Pull request closed without merging**
