### PR TITLE
Add documentation on building uberjars to README

### PR DESCRIPTION
**Pull request by bo-tato**
link documentation for building uberjars https://github.com/babashka/neil/issues/140

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks!

**Comment by bo-tato** [comment]
thanks! I just realized it's not actually in the readme as I just edited README.template.md and didn't run the 'update-readme' task

**Comment by borkdude** [comment]
Ah, can you fix this?

**Comment by bo-tato** [comment]
sure, I just ran `bb update-readme` and submited new pull request. It seems `update-readme` runs first `gen-script` which added to `neil` another small change you did recently in `neil.clj`

**Pull request merged**
