### PR TITLE
Ydl refactor

### PR DESCRIPTION
**Pull request by yisraeldov**
Factoring out some repeated code.

Would be nice to move lots of these functions for accessing remote APIs to a separate namespace, 

I couldn't figure out how to do this with `uberscript`.

### CODE REVIEW

**Comment by borkdude** [comment]
@yisraeldov The source in src/* can contain an arbitrary amount of namespaces. Then `bb uberscript` will assemble those into one file `neil`. Maybe we should remove the generated script from source control.

**Comment by yisraeldov** [comment]
Yeah, the generated script should probably be removed from source
control and let the CI generate it.

I tried putting new files in `src/neil/http.clj` and then required
`babashka.neil.clj` and the built script couldn't find the namespace.

**Comment by borkdude** [comment]
That namespace should be called `neil.http`, not `babashka.neil`

**Comment by borkdude** [comment]
You should add the file in `src/babashka/neil/http.clj`

**Comment by yisraeldov** [comment]
yeah, sorry that is what I did.

**Pull request merged**
