### PR TITLE
Use uberjar for packages

### LINKED ISSUE #49: consider using uberjar for brew package
Then we dont't need to do any add-deps stuff at runtime any more and it becomes more self-contained.

/cc @littleli

### PR DESCRIPTION
**Pull request by rads**
Resolves #49 and #70.

## Overview

I only made the minimal changes to start publishing as an uberjar. Since the `neil.jar` file is not executable without a wrapper script, the actual artifact is a `neil.zip` file which includes the `neil` script in addition to the JAR.

I think if we want to do more cleanup, such as decoupling the tests from the `./neil` script, we should merge in this PR first. That way we will get the benefit of cleaner PRs and we can get the package manager stuff out of the away as soon as possible.

## Examples

Replace the `rads` references in the examples with `borkdude` or `babashka` as needed.

`neil`:
```clojure
 ;; The prefix var is a placeholder for package managers such as Homebrew.
(def prefix nil)

(def root
  (str (or prefix
           (str ((requiring-resolve 'babashka.fs/parent) *file*) "/"))
       "neil.jar"))

(babashka.deps/add-deps {:deps {'org.babashka/neil {:local/root root}}})

((requiring-resolve 'babashka.neil/-main))
```

`neil.rb`:
```ruby
class Neil < Formula
  def install
     inreplace "neil", "(def prefix nil)", "(def prefix \"#{prefix}/\")"
     prefix.install "neil.jar"
     bin.install "neil"
   end
end
```

Build:
```
$ echo "0.1.44" > version.txt

$ bb tag
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:rads/neil.git
 * [new tag]         v0.1.44 -> v0.1.44
 
$ bb upload-release
Producing uberjar
updating: neil.jar (deflated 13%)
updating: neil (deflated 29%)

$ open https://github.com/rads/neil/releases/tag/v0.1.44
```

## Related

- https://github.com/rads/neil/releases/tag/v0.1.44
- https://github.com/babashka/homebrew-brew/pull/2

### CODE REVIEW

**Comment by rads** [comment]
@borkdude: I was doing some testing and ran into the following issue when using the JAR. It looks like external templates are working but the built-in templates are not:
```
$ neil new io.github.rads/neil-new-test-template foo2 --latest-sha
Creating project from io.github.rads/neil-new-test-template in foo2

$ neil new scratch foo
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Unable to find template.edn for org.corfield.new/scratch
Data:     {}
Location: org/corfield/new.clj:54:11

----- Context ------------------------------------------------------------------
50:         (impl/preprocess-options opts)
51:         [dir edn-file] (impl/find-root template)
52:         _
53:         (when-not dir
54:           (throw (ex-info (str "Unable to find template.edn for " template) {})))
              ^--- Unable to find template.edn for org.corfield.new/scratch
55:
56:         [{:keys [target-dir template-dir overwrite] :as final-opts} edn]
57:         (impl/apply-template-fns dir
58:                                  basic-opts
59:                                  ;; this may throw for invalid EDN:

----- Stack trace --------------------------------------------------------------
babashka.neil.new/deps-new-create - babashka/neil/new.clj:139:1
babashka.neil.new                 - babashka/neil/new.clj:220:13
babashka.neil                     - babashka/neil.clj:498:3
user                              - /Users/rads/src/neil/neil:14:1
```

I was able to get it working again with the uberjar by adding an explicit `add-deps` call even for built-in templates. That said, I'm not sure what the root cause is yet, and I'm hoping you might have a better idea.

**Comment by borkdude** [comment]
@rads I suspect this has to do with how deps-new works: it probably expects the templates to live on disk and not inside a jar.

cc @seancorfield: for context, we are trying to distribute neil as a jar for package managers, so we don't have to check in the "compiled" script into source control on each commit.

Perhaps we should conclude that the way how we're currently distributing neil is the least problematic.

**Comment by borkdude** [comment]
@rads I guess we could also generate the `add-deps`-based script fully within the brew formula and hold the template under version control, so in the brew formula the SHA and tag are replaced and then that script is installed.

**Comment by rads** [comment]
@borkdude:
> I suspect this has to do with how deps-new works: it probably expects the templates to live as files in a directory and not inside a jar.

Ah yes, that makes sense. It's the same reason we can't support templates with Maven coordinates.

> Perhaps we should conclude that the way how we're currently distributing neil is the least problematic.

One more idea before we give up on this approach:

Since deps-new has special behavior, what if we load this particular dep exclusively as an `add-deps` call, but leave the rest of the deps in the classpath? We could avoid duplicating the lib coordinates this way since the deps-new version would only be stored in one place (the `babashka.neil` namespace). It also wouldn't break any existing behavior since we fetch _all_ the deps at runtime now.

**Comment by borkdude** [comment]
Or we could extract some of the built-in stuff to a `~/.neil/resources` directory and add this directory to the classpath.
Or we could extract neil.jar (since it's a zip file) into the installation directory entirely.

**Comment by rads** [comment]
@borkdude:
> I guess we could also generate the add-deps-based script fully within the brew formula and hold the template under version control, so in the brew formula the SHA and tag are replaced in the template and then that script is installed.

I think we want to pre-generate as much as possible before we upload the release artifact. That way we keep our requirements for package managers minimal.

If we wanted to use a script instead of an uberjar with this PR, we could check-in a template and fill it in when we publish to GitHub releases. The uploaded artifact would be created _after_ the tag, meaning end users would see `v0.1.44` and the short SHA in the `neil` source, but this information is not needed in the Git repo itself.

**Comment by rads** [comment]
> Or we could extract some of the built-in stuff to a ~/.neil/resources directory and add this directory to the classpath.
> Or we could extract neil.jar (since it's a zip file) into the installation directory entirely.

It feels like we'd be adding weird stuff to the installation process just to support bundling deps-new in an uberjar. I would probably prefer a generated script rather than adding more complexity here. For me it's best if the package manager steps are minimal since it's difficult for me to test and maintain these scripts relative to the `neil` code itself.

**Comment by seancorfield** [comment]
@rads Yes, @borkdude is correct that because `deps-new` is built on `tools.build`, the template files must exist on the file system which means that `deps-new` itself needs to be a `:local/root` or `:git/sha` style dependency -- it can't be bundled into a JAR and still work.

**Comment by borkdude** [comment]
Thanks for the confirmation @seancorfield. 

I'm going to close this PR as I don't think changing the current way of packaging will greatly improved it. We can continue the discussion [here](https://github.com/babashka/neil/discussions) if you feel there's more to say about changing things.

**Comment by rads** [comment]
@borkdude: All good, there's plenty of other stuff to work on. 🙂

**Comment by rads** [comment]
I see that #49 and #70 were closed so I'll take that as a win! 😉

**Pull request closed without merging**
